services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - 4533:4533
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "/mnt/nas/media/music:/music:ro"
    networks:
      - proxy

networks:
  proxy:
    name: proxy_network
    external: true
