services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - proxy
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/nas/data
        target: /data
    restart: 'unless-stopped'

  # jellyseerr:
  #   container_name: jellyseerr
  #   image: fallenbagel/jellyseerr:latest
  #   networks:
  #     - servarrnetwork
  #     - proxy
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - ./jellyseerr:/app/config
  #   ports:
  #     - 5055:5055
  #   restart: unless-stopped


networks:
  proxy:
    name: proxy_network
    external: true
