services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env

